# Generated by Django 3.1 on 2020-12-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_auto_20201228_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='alarm',
            field=models.BooleanField(default=False),
        ),
    ]
