# Generated by Django 3.1 on 2021-01-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_auto_20210103_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='alarm',
            field=models.DateTimeField(null=True),
        ),
    ]
